### ISSUE TITLE
Cert issue with pfsense

### ISSUE THREAD

**Issue by nkleck** [davidemyers/algo-pfsense#2] opened 2020-02-01 00:35 UTC
David,

Ive followed your post back around Oct or Nov2 018 and built a VPN for an internal lab I have. The idea was an internal network segregated from my other networks via an internal pfsense server, and all hosts in those networks were VPNd out. I'm in the process of rebuilding the lab and have been unable to get the pfsense - algo (vps) VPN working this time around. I have been stuck on this one for days.

pfsense: 2.4.4-RELEASE-p3 (but i also tried on 2.4.3)
algo: ubuntu 18.04 in aws - t2.micro

AWS Security Group Rules
```
Custom UDP Rule	UDP	51820	<MY_IP>32	WireGuard
Custom UDP Rule	UDP	1701	<MY_IP>/32	UDP Port 1701 (L2T...
SSH             TCP	22	<MY_IP>/32	ssh
Custom UDP Rule	UDP	4500	<MY_IP>/32	IPSEC NAT-Traversa...
Custom UDP Rule	UDP	500	<MY_IP>/32	UDP Port 500 (IKE)
```

10.10.50.10 is the WAN IP of my internal pfsense VM

Im not sure, but i think something is going wrong with the certs?
```
Feb 1 00:21:42 	charon 		12[ENC] <con1000|2> parsed IKE_AUTH response 1 [ IDr CERT AUTH SA TSi TSr ]
Feb 1 00:21:42 	charon 		12[IKE] <con1000|2> received end entity cert "CN=54.171.233.188"
Feb 1 00:21:42 	charon 		12[CFG] <con1000|2> using certificate "CN=54.171.233.188"
Feb 1 00:21:42 	charon 		12[CFG] <con1000|2> certificate "CN=54.171.233.188" key: 384 bit ECDSA
Feb 1 00:21:42 	charon 		12[CFG] <con1000|2> no issuer certificate found for "CN=54.171.233.188"
Feb 1 00:21:42 	charon 		12[CFG] <con1000|2> issuer is "CN=54.171.233.188"
Feb 1 00:21:42 	charon 		12[IKE] <con1000|2> no trusted ECDSA public key found for '54.171.233.188'
Feb 1 00:21:42 	charon 		12[ENC] <con1000|2> generating INFORMATIONAL request 2 [ N(AUTH_FAILED) ]
Feb 1 00:21:42 	charon 		12[NET] <con1000|2> sending packet: from 10.10.50.10[4500] to 54.171.233.188[4500] (65 bytes)
Feb 1 00:21:42 	charon 		12[CHD] <con1000|2> CHILD_SA con1000{3} state change: CREATED => DESTROYING
Feb 1 00:21:42 	charon 		12[IKE] <con1000|2> IKE_SA con1000[2] state change: CONNECTING => DESTROYING
```

Thoughts? I am adding cacert.pem to the pfsense Cert Manager under the CA section > Certificate Data box (nothing in the private key box for CA). 

I am also uploading the router cert by adding the Cert and Key portions to their respective boxes (including the --BEGIN-- and --END-- lines). I have tried it both, with and without the Bag Attributes, subject, and issuer lines. 

I even added the patch you created here
https://github.com/msmollin/algo/issues/1#issuecomment-312431463

Full pfsense ipsec and algo vps logs are attached
[pfsense_ipsec_log.txt](https://github.com/davidemyers/algo-pfsense/files/4141954/pfsense_ipsec_log.txt)
[vps_logs.txt](https://github.com/davidemyers/algo-pfsense/files/4141955/vps_logs.txt)

**Comment by davidemyers** [comment] 2020-02-01 01:28
There was a recent change to Algo in [PR #1675](https://github.com/trailofbits/algo/pull/1675) that changed aspects of the CA, and maybe that broke things. Try using a copy of Algo from before that PR.

I'm going to have to spend some time to see what needs to change to make these instructions work with the revised CA, if indeed that's still possible.

**Comment by nkleck** [comment] 2020-02-01 14:44
Thanks David,

I reverted to the commit prior to that merge. The vpn is working great.

https://github.com/trailofbits/algo/tree/0e57da8237488399a0b446349df12f43327aac36

**Comment by randomdross** [comment] 2020-09-07 01:52
I'm hitting the exact same issue.  Would prefer not to stay on an old version of Algo if possible.  @davidemyers  any luck figuring out what's up?  I wonder if at this point it's worth switching from ipsec to wireguard.

**Comment by randomdross** [comment] 2020-09-07 04:52
Yeah, it's definitely https://github.com/trailofbits/algo/pull/1675 that's the problem.  I forked the repo with that change reverted (here: https://github.com/randomdross/algo) and that resolves the issue.  Wondering if a proper fix should live in pfsense, strongswan, or ?  (Not immediately sure where to file a bug.)

**Comment by randomdross** [comment] 2020-09-07 05:05
Incidentally, while removing the change from algo worked to resolve the issue, relaxing the CA constraints in pfsense by setting enforce_critical to 'no' did not resolve the issue.  (That is, I tried to set strongswan configuration in pfsense as per https://github.com/trailofbits/algo/commit/4f1b9270be99f2323d13ec42a6276bb522037361 but it didn't fix the issue.)  Maybe I just didn't do that properly, not sure...  It seems like a correct fix should be something like this on the pfsense side, rather than reverting the change in algo.

**Comment by randomdross** [comment] 2020-09-07 05:29
Filed a pfsense bug: https://redmine.pfsense.org/issues/10873

**Comment by davidemyers** [comment] 2020-09-07 11:22
@randomdross Thanks for digging into this, I hadn't gotten around to it. I think I might just modify the instructions to include reverting the change to Algo. Is this sufficient:
```
git revert -n 0efa4eaf9175f4345fb8d81eb1d3c6205a57048e
```

**Comment by randomdross** [comment] 2020-09-07 17:12
Haven't tried that specifically, but I believe it would work.  Sounds good to just add into the instructions for now, maybe referencing https://redmine.pfsense.org/issues/10873 or this bug.

**Comment by davidemyers** [comment] 2020-09-07 22:50
That revert command worked for me so I modified the instructions.

**Comment by yummy-ja** [comment] 2020-11-06 22:36
@davidemyers The instructions didn't work for me, I still get the same errors with "no trusted ECDSA public key found" in the PFSENSE logs. Also, using the git revert command you provided gave me conflict errors for the config.cfg file so the revert didn't work. What I did end up running that worked is the following command:

`git reset --hard 0e57da8237488399a0b446349df12f43327aac36`

I disabled the Wireguard setup in my config.cfg file b/c I only use IPsec, but if I wanted to use Wireguard I would also needed to edit the algo/roles/wireguard/tasks/ubuntu.yml file to [match the current one in the Algo repo](https://github.com/trailofbits/algo/blob/master/roles/wireguard/tasks/ubuntu.yml).

I'm using Linode with Ubuntu 18.04 LTS, trying the above setup with the latest release of Ubuntu threw other errors for the Algo setup (I didn't bother tracing those out, as I am OK with using 18.04 LTS for this setup.)

If you think this issue caused by something on the PFSENSE side let me know and maybe I can dig around and help identify the bug.

**Comment by davidemyers** [comment] 2020-11-08 00:38
How about if you use the `git revert` command above, ignore the errors, then run:
```
git restore --staged config.cfg
git checkout -- config.cfg
```

**Comment by yummy-ja** [comment] 2020-11-08 07:21
@davidemyers Thanks, that change did work. I also went ahead and took a dive and found the issue with this not working with Ubuntu 20.04 LTS. The issue is with roles/common/tasks/freebsd.yml, line 45 task to Install Tools, it needed the option to run with sudo.

I was playing around with other settings and found that I could connect via IPv6. Am I wrong that this may open up the ability to use VTI for PFSENSE? I haven't researched this one much, so my testing was limited, but it does seem to work. It would need more testing and configuring but I thought I would drop the idea here to see your thoughts.

**Comment by davidemyers** [comment] 2020-11-08 13:45
Thanks for testing the change, I've revised the instructions.

**Comment by davidemyers** [comment] 2021-01-28 13:59
I've just added instructions for using WireGuard which is in pfSense 2.5. I'm going to close this issue.

**Closed by davidemyers** 2021-01-28 13:59 UTC
